### ISSUE TITLE
Link to GitHub project is broken

### ISSUE THREAD

**Issue by indigo423** [grafana/design-system#87]
When you click the link to the GitHub project you get a 404 not found. 

Link: [Github project](https://github.com/orgs/grafana/projects/176/views/4) 

<img width="1589" alt="Screenshot 2023-11-08 at 01 14 00" src="https://github.com/grafana/design-system/assets/1095181/a5f056d5-c9cd-4dbf-a4dc-5b35c25121a2">

**Comment by Clarity-89** [comment]
The link is correct, it's probably the project that's private cc @staton-hyse11.

**Comment by staton-hyse11** [comment]
The GH project is set to private at the moment. Currently working with Admins to get it switched over to public-access
