### ISSUE TITLE
Saga: link out to Voice and Tone 

### ISSUE THREAD

**Issue by staton-hyse11** [grafana/design-system#90]
To avoid maintaining the same content in two places, we should ink the Voice and Tone section to the Writer's Toolkit on the docs site.

- [ ] Remove the Voice and Tone page content and page
- [ ] Create a link in the left nav for Voice and Tone
- [ ] Link to [here](https://grafana.com/docs/writers-toolkit/write/style-guide/voice-tone-guidelines/)
- [ ] Include an "external link icon" to imply to users they are leaving the site

**Comment by JoaoSilvaGrafana** [comment]
Think you went with the right solution 👍  Dont want to overcomplicate the nav just for this one scenario
